---
title: "Blog Posts"
output:
  html_document: 
    toc: true
    toc_float: true
---

## Blog 1
### 5/6/2020: A Snapshot of Illegal Construction work in San Francisco
Story time: It all started when my family was recently in the business of potentially buying a new property. Last winter break, I spent several days with my family touring open houses and it was always interesting to find the "bonus" rooms hidden away in houses, originally not advertised. At first glance (if you were ignorant like me), you would get that same exciting rush you get from finding the one curly fry tucked in a heap of regular fries. Can it be that you might be the lucky winner? Can buying a house really involve BOGO bedroom deals? Curious at this mystery, I asked my father, heavily involved in the hardware business, why they wouldn't advertise an essentially full extra unit dwelling unit downstairs. The answer was quite simple: illegal construction without a building permit. Or more simply, the blueprints to the current house don't match what city hall has filed away in their cabinets.

Having grown up in San Francisco, anecdotally, when you walk into a single-family home in the Sunset or the Richmond neighborhoods, it wouldn't be surprising to see a bedroom or bathroom added to the original construction. This isn't surprising as many sunset-neighborhood units were originally built as 2 bedroom/1 bathroom units, small by today's standards for an American family; so adding extra rooms makes sense, whether or not the work was done in a legal manner is up to question. 

Being on the market to possibly rent somewhere in the city, I've seen several postings include in their descriptions the now infamous "bonus rooms" line. Natural curiousity pushed me to see if I can get a gauge on how prevalent illegal construction is/was in San Francisco. Conveniently, I discovered that every building permit filed going back several decades was compiled into a dataset that is public and open for anyone to download. (Link at the bottom). For every permit, there is a short description of the work to be done for that particular project. Based on the description, I searched for two words: "illegal" and "legalize" in the permits from single family, two-family, and apartment properties to map out where illegal construction work has been done. This was all compiled into an R Shiny Web App for visualization. Once on the app, choose a neighborhood and property type to display the markers of properties involved with illegal construction, sorting by permit year may be interesting to you as well. Hover over and click a marker to read the project description from that particular building permit. Feel free to play around!

<iframe src="https://zeloszhu.shinyapps.io/sf_permits_illegalhomes/" width="90%" height="400px"></iframe>

Open this R Shiny on a new tab: [[Link]](https://zeloszhu.shinyapps.io/sf_permits_illegalhomes/)

Data available at: [[Link]](https://data.sfgov.org/Housing-and-Buildings/Building-Permits/i98e-djp9)